### ISSUE TITLE
Nice buddy!

### ISSUE THREAD

**Issue by fukunee** [SleepyPrince/OctopathTravelerSaveTemplate#1]
Proved awesome in my save!
Thanks for your work!

I noticed that the item struct' length is 2,000 limited. If have owned over 2000 types of items... I'm curious about what will happen. :)

**Comment by SleepyPrince** [comment]
Thanks. So far we have only found 661 item IDs, so that shouldn't be a problem.

**Comment by fukunee** [comment]
Got it！
